### ISSUE TITLE
Welcome画面：「活用例（仮）」コンポーネントのスタイル作成

### ISSUE THREAD

**Issue by mihye1128** [camp-team/twitter-project#11]
## Todo

- Welcomeコンポーネントから切り離して、「活用例（仮）」のコンポーネントを作成してください。
- 下記の修正をお願いします。

### 修正依頼
- `.container`の中に`.about`よりは、`.about`の中に`.container`の方がいいですね。理由は、背景色を入れたりなど、全体に伸びる背景が使えるようになるので、デザイン調整する時に汎用的になります！
- （コンポーネントを分けるので関係なくなる話ですが、）できれば、BEMで、`.about__title`や `.about__text`がいいと思います。もしかしたら、こちらで汎用的なクラスを使うかもしれないので、`.title`と`text`は一旦置いておいて、カードの部分を優先的に作業していただけるとありがたいです！

**Comment by K-Yuki1019** [comment]
@mihye1128 

かしこまりました！
ご指摘頂いた部分取り掛かります。
ありがとうございます！

**Comment by mihye1128** [comment]
GJ!!
