### ISSUE TITLE
デザイン調整

### ISSUE THREAD

**Issue by mihye1128** [camp-team/twitter-project#22]
## Todo
- サービス名決定
- メインカラー決定
- トップページデザイン調整
- 今日の目標ページデザイン調整

**Comment by mihye1128** [comment]
@K-Yuki1019 @komura-c 
お疲れ様です！

サービス名、「爆たす」を入れてみました！
入れたところ、LPの方向性が見えてきて、
ファビコンも💣にしたらいいし、まとまりそうな予感がしました！
「爆たす」で決定いいかなと思ってます、いかがですか？

メインカラー案を作成しました！
「爆たす」という名前からして、危険カラーかと思ったので、オレンジ・赤からチョイスしました。
個人的には、Orengeがギリギリ目に痛くないかなと思います。
DeepOrangeの方がぽいけど、きついかなと。
いかがでしょうか？

現在
![image](https://user-images.githubusercontent.com/46749854/94024813-cb1fe700-fdf2-11ea-9120-0609dbf326be.png)

Orange(MaterialDesign)
![image](https://user-images.githubusercontent.com/46749854/94026932-45516b00-fdf5-11ea-8d40-3e9c7fbeadd5.png)

DeepOrange(MaterialDesign)
![image](https://user-images.githubusercontent.com/46749854/94027390-c0b31c80-fdf5-11ea-9eab-109853016c21.png)

Red(MaterialDesign)
![image](https://user-images.githubusercontent.com/46749854/94025020-06221a80-fdf3-11ea-844b-3ebf43d51649.png)

**Comment by komura-c** [comment]
@mihye1128 お疲れ様です！！おおお！！凄くよいですね！！個人的にはDeepOrangeもいいと思いますが、確かに少し刺激が強い感じするのでやはりOrangeがよさそうですね〜！あ、でも今の黄色も危険感⚠️伝わるのでいい気もします🤔

**Comment by mihye1128** [comment]
ありがとうございます！なるほど！
黄色は、bosyuの色なんですよね。流石にそのままじゃまずいかなと思ったので、materialのYellowで作ってみました！
<img width="1279" alt="スクリーンショット 2020-09-24 8 01 56" src="https://user-images.githubusercontent.com/46749854/94082636-5d001200-fe3c-11ea-874f-d3d566a0c10a.png">

**Comment by komura-c** [comment]
なるほど！ありがとうございます🙏お！！materialのYellowいいんじゃないでしょうか！！
