### ISSUE TITLE
(CatchCopy)サイト下部のキャッチコピーコンポーネント作成 

### ISSUE THREAD

**Issue by K-Yuki1019** [camp-team/twitter-project#23]
ライティング部分を考えます。

## Todo

- [ ] ルーティング
- [x] マークアップ

## 参考イメージ
![image](https://user-images.githubusercontent.com/63516648/94133097-2ad1cd00-fe9b-11ea-9b46-638198457383.png)

## Docs

- [オリジナルサービスを開発する](https://to.camp/lesson?v=fBTqHPE1BIwHb8BAgD1Q&cause=h593RfPIXvL5SXaxLkGI)

**Comment by mihye1128** [comment]
GJ!!
